### PR TITLE
skyboxes

### PR DESCRIPTION
**Pull request by ThePerfectTrip**
;)

### CODE REVIEW

**Review by drzel — CHANGES_REQUESTED** [review]
I think skyboxes belong in `fortress/env/`.

**Comment by ThePerfectTrip** [comment]
either way will work, but we can go with that!

**Comment by ThePerfectTrip** [comment]
textures for tfc_2fort_b5 and skyboxes + cfg!

**Comment by ThePerfectTrip** [comment]
tfc_2fort_b5 textures + skyboxes and cfg file!

**Review by drzel — APPROVED** [review]

**Pull request merged**
